// export const en = {
// 	hello: "Hello",
// 	we_have_good_news: 'We have good news',
// }

// export const ru = {
// 	hello: "Привет",
// 	we_have_good_news: 'У нас хорошие новости',
// }

// export const ua = {
// 	hello: "Привіт",
// 	we_have_good_news: 'Ми маємо добрі новини',
// }

var data = [
{
	hello: "Well,",
	we_have_good_news: 'We have good news',
	do_not: "I don't want to participate in this event.",
	inputEmail: "Join",
	subscribers: "Subscribers",
	is_subscribe: "You are subscribed",
	unsubscribe: "Unsubscribe",
	error_email: "Email is incorrect",
	text_for_email: `You need only specify your email and click "OK"`,
	email_placeholder: "Please enter your Email",
	in_theme: "I'm in",
	ok: "Ok",
	change_profile: "Change profile",
	settings: "Settings",
	remove_profile: "Remove profile",
	i_want: "I want to take part in the event!",
	subscribe_description: `To subscribe you should specify your Email, to which will be sending some changes such as comments and new subscribes.
	It will also help to know a quantity involved. Don't forget to subscribe.  `,
	isSure: "Are You sure you want to remove your profile? \n\nAfter removing your profile it will be unsubscribed from all events",
	subscribers_ad: "The list of subscribers on the event: ",
	time_to_start: "Countdown",
	time_to_start_ad: "The event will start in: ",
	days: "D",
	hours: "H",
	minutes:"M",
	seconds: "S",
	comments: "Comments",
	remove: "Delete",
	add_comment: "Add comment",
},
{
	hello: "И так,",
	we_have_good_news: 'У нас хорошие новости',
	do_not: 'У меня нет намерений учавстовать в этом событии',
	inputEmail: "Хочу принять участие",
	subscribers: "Уже участвуют",
	is_subscribe: "Вы уже подписаны",
	unsubscribe: "Отписаться",
	error_email: "Email неверный",
	text_for_email: `Все что нужно - это указать Email и нажать кнопку "OK"`,
	email_placeholder: "Email",
	in_theme: "Скидываюсь",
	ok: "Подписаться",
	change_profile: "Изменить профиль",
	settings: "Настройки",
	remove_profile: "Удалить профиль",
	i_want: "Хочу учавстовать!",
	subscribe_description: `Чтобы подписаться нужно будет указаь E-mail, на который в случае каких-либо изменений, придет сообщение.
	Так же это нужно для учета количества учасников, так что не забудь подписаться. `,
	isSure: "Вы действительно желаете удалить профиль? \n\nПосле удаления вы будете отписаны от всех событий на сайте",
	subscribers_ad: "Список участников: ",
	time_to_start: "Время до начала",
	time_to_start_ad: "Событие начнется через: ",
	days: "Д",
	hours: "Ч",
	minutes:"М",
	seconds: "С",
	comments: "Комментарии",
	remove: "Удалить",
	add_comment: "Добавить комментарий",
},
{
	hello: "Так ось,",
	we_have_good_news: 'Ми маємо добрі новини',
	do_not: 'Мене ця подія не цікавить',
	inputEmail: "Хочу прийняти участь",
	subscribers: "Приймають участь",
	is_subscribe: "Ви підписані на цю подію",
	unsubscribe: "Відписатися",
	error_email: "Email невірний",
	text_for_email: `Потрібно тільки ввести ваш Email і натиснути кнопку "OK"`,
	email_placeholder: "Email",
	in_theme: "Згоден скинутися грошима",
	ok: "Підписатися",
	change_profile: "Змінити профіль",
	settings: "Налаштування",
	remove_profile: "Видалити профіль",
	i_want: "Я хочу прийняти в цьому участь!",
	subscribe_description: `Щоб підписатися потрібно вказати E-mail, на який будуть надходити зміни.
	Це також потрібно для підрахунку кількості людей які будуть приймати участь у події. `,
	isSure: "Ви дійсно бажаєте видалити профіль? \n\nПісля видалення ви будете автоматично відписані від усіх подій",
	subscribers_ad: "Приймають участь: ",
	time_to_start: "Час до початку",
	time_to_start_ad: "Подія почнеться через: ",
	days: "Д",
	hours: "Г",
	minutes:"Х",
	seconds: "С",
	comments: "Коментарі",
	remove: "Видалити",
	add_comment: "Додати коментар",
}
];

module.exports = data;
